export const itemValues = {
  "archers ring": 10,
  "warrior ring": 10,
  "berserker ring": 10,
  "seers ring": 10,
  "abyssal whip": 10,
  "kraken tentacle": 10,
  "occult necklace": 10,
  "hueycoatl hide": 10,
  "dragon hunter wand": 10,
  "tome of earth (empty)": 10,
  "fire element staff crown": 10,
  "ice element staff crown": 10,
  "mystic vigour prayer scroll": 10,
  "deadeye prayer scroll": 10,
  "uncut onyx": 10,
  "dragon chainbody": 10,
  "odium shard 1": 10,
  "odium shard 2": 10,
  "odium shard 3": 10,
  "abyssal dagger": 30,
  "saradomin hilt": 30,
  "bandos hilt": 30,
  "zamorak hilt": 30,
  "armadyl hilt": 30,
  "primordial crystal": 30,
  "pegasian crystal": 30,
  "eternal crystal": 30,
  "smouldering stone": 30,
  "blood shard": 30,
  "zenyte shard": 30,
  "tanzanite mutagen": 30,
  "magma mutagen": 30,
  "staff of the dead": 30,
  "zamorakian spear": 30,
  "burning claw": 30,
  "tormented synapse": 30,
  lightbearer: 30,
  jar: 30,
  "bandos chestplate": 30,
  "bandos tassets": 30,
  "armadyl helmet": 30,
  "armadyl chestplate": 30,
  "armadyl chainskirt": 30,
  "bludgeon claw": 30,
  "bludgeon spine": 30,
  "bludgeon axon": 30,
  "dragon pickaxe": 30,
  "dragonbone necklace": 30,
  "serpentine visage": 30,
  "black tourmaline core": 30,
  "magic fang": 30,
  "tanzanite fang": 30,
  "crystal armour seed": 30,
  "dragon warhammer": 50,
  "craw's bow (u)": 50,
  "thammaron's sceptre (u)": 50,
  "viggora's chainmace (u)": 50,
  "twisted buckler": 50,
  "elidinis' ward": 50,
  "hydra claw": 50,
  "hydra leather": 50,
  "basilisk jaw": 50,
  "armadyl crossbow": 50,
  "voidwaker blade": 50,
  "voidwaker gem": 50,
  "voidwaker hilt": 50,
  "dragon full helm": 50,
  "sunfire fanatic helm": 50,
  "sunfire fanatic cuirass": 50,
  "sunfire fanatic chausses": 50,
  "justiciar faceguard": 50,
  "justiciar chestguard": 50,
  "justiciar legguards": 50,
  "soulflame horn": 50,
  "noxious point": 50,
  "noxious blade": 50,
  "noxious pommel": 50,
  "araxyte fang": 50,
  "leviathan's lure": 100,
  "siren's staff": 100,
  "executioner's axe head": 100,
  "eye of the duke": 100,
  "venator vestige": 100,
  "bellator vestige": 100,
  "ultor vestige": 100,
  "magus vestige": 100,
  "osmumten's fang": 100,
  "avernic defender hilt": 100,
  "sanguinesti staff": 100,
  "ghrazi rapier": 100,
  "ancient hilt": 100,
  "eye of ayak (uncharged)": 100,
  "mokhaiotl cloth": 100,
  "virtus mask": 100,
  "virtus robe top": 100,
  "virtus robe bottom": 100,
  "oathplate helm": 100,
  "oathplate chest": 100,
  "oathplate legs": 100,
  "dexterous prayer scroll": 100,
  "arcane prayer scroll": 100,
  "nightmare staff": 100,
  "dragon claws": 150,
  "dragon hunter crossbow": 150,
  "eldritch orb": 150,
  "harmonised orb": 150,
  "volatile orb": 150,
  "inquisitor's great helm": 150,
  "inquisitor's hauberk": 150,
  "inquisitor's plateskirt": 150,
  "inquisitor's mace": 150,
  "zaryte vambraces": 300,
  "nihil horn": 300,
  "torva full helm (damaged)": 300,
  "torva platebody (damaged)": 300,
  "torva platelegs (damaged)": 300,
  "dinh's bulwark": 150,
  "enhanced crystal weapon seed": 150,
  "eternal gem": 150,
  "draconic visage": 150,
  "skeletal visage": 150,
  "wyvern visage": 150,
  "masori mask": 150,
  "masori body": 150,
  "masori chaps": 150,
  "ancestral hat": 150,
  "ancestral robe top": 150,
  "ancestral robe bottom": 150,
  "spectral sigil": 350,
  "arcane sigil": 350,
  "dizana's quiver (uncharged)": 350,
  "infernal cape": 350,
  "elder maul": 350,
  "avernic treads": 350,
  "imbued heart": 350,
  "kodai insignia": 350,
  "tonalztics of ralos (uncharged)": 350,
  pet: 350,
  "twisted bow": 600,
  "scythe of vitur (uncharged)": 600,
  "tumeken's shadow": 600,
  "elysian sigil": 600,
};
